name: Mirror Repository

on: push
jobs:
  repo-sync:
    runs-on: ubuntu-latest
    steps:
    - name: repo-sync
      uses: wei/git-sync@v1
      env:
        SOURCE_REPO: "https://github.com/lizalexandrita/Knowledge-Graph.git"
        SOURCE_BRANCH: "main"
        DESTINATION_REPO: "https://github.com/new-atlantis-labs/Knowledge-Graph.git"
        DESTINATION_BRANCH: "main"
        SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
      with:
        args: $SOURCE_REPO $SOURCE_BRANCH $DESTINATION_REPO $DESTINATION_BRANCH

