name: Mirror Repository

on: [push]

jobs:
  mirror:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2
    - name: Mirror Repository
      uses: wei/git-sync@v1
      env:
        SOURCE: "https://github.com/lizalexandrita/Knowledge-Graph.git"
        DESTINATION: "https://github.com/new-atlantis-labs/Knowledge-Graph.git"
        SECRET_NAME: ${{ secrets.SSH_PRIVATE_KEY }}